### ISSUE TITLE
List: no single/double click actions for list items

### ISSUE THREAD

**Issue by jillyan** [Talend/react-talend-components#244]
according to guidlines, each item in list has the following actions:
 Single click on item background selects it.
 Double click on item background opens it.
http://guidelines.talend.com/document/92132#/navigation-layout/list

But now, there are no single or double click actions.

I tried to add onClick into related tr/div, it will get eslint-disable-line jsx-a11y/no-static-element-interactions error. And another pb, the input checkbox's onChange will trigger this onClick as well, so if user checked the checkbox, it would select the same item two times.
ah, really like a stalement

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#45
