### ISSUE TITLE
List component display table HTML structure

### ISSUE THREAD

**Issue by amaalej** [Talend/react-talend-components#41]
@jmfrancois Thank you very much for your contribution on the List component, however I have a some remarks about the Structure in the component:

Using the `<table>` tag, adds more constraints to the List component display, so I think it would be more flexible if we use flex to display the list items and to avoid the colspan headaches.

What do you think?

**Comment by frassinier** [comment]
In fact, if you can read data in two dimensions then it means you can display it as table. It's not an issue, IMO semantic is correct.
For your second point, `display: flex` will be easier to deal with, I would be curious to know how you will plan to keep same size between each cell for each column without fixing its size?

**Comment by jsomsanith** [comment]
@amaalej Can you give an example that you find painful to use the component and how it would be solved with flex ? And what would be the input of the component to configure that.

**Comment by jmfrancois** [comment]
Please could you give me more facts, I really don't understand the problem

> Using the <table> tag, adds more constraints to the List component display

What constraints ?

>  so I think it would be more flexible if we use flex to display the list items

could you please give me an example of a list of items using flex which is displayed like a table ?

> the colspan headaches

I don't know this issue.

The Table display don't follow our guidelines at the moment.
The goal was to have a first simple version, so it's true, it's far from perfect at the moment.

We will do multiple iterations to improve all display modes
So fill free to contribute throw PR and discuss the goal first (our guidelines) with our UX guys

We want full features List rendering which is expose a great API.

Missing features at the moment are

* Infinite scroll (may be should be done in a different component, must be discussed first)
* Fix the table head when scrolling
* onSelect handler
* styling

**Comment by amaalej** [comment]
Ok, I close the issue for the moment
