### ISSUE TITLE
bug(List): safari

### ISSUE THREAD

**Issue by jmfrancois** [Talend/react-talend-components#54]
The toolbar of the list is broken on safari.

The markup is inconsistent: some **buttons** inside **ul**.

![screen shot 2016-10-24 at 17 19 39](https://cloud.githubusercontent.com/assets/19857479/19651660/1451c2ba-9a0e-11e6-8c5a-e24b3a405cd7.png)

**Comment by sdwvit** [comment]
👍  And update: 
<img width="1332" alt="2016-12-09 19 39 59" src="https://cloud.githubusercontent.com/assets/8777372/21058604/6f2dbbd2-be47-11e6-8c7b-4159a9e28c99.png">
this is critical enough
