### ISSUE TITLE
bug(List): Action click handler parameter

### ISSUE THREAD

**Issue by yyanwang** [Talend/react-talend-components#62]
When Action's click handler triggered, model should be passed to handler function, according this:

https://github.com/Talend/react-talend-components/blob/master/src/Action/Action.component.js#L29

but in fact, model is always undefined, so in handler function I don't know which item the action is apply to.
you can see model is missing when onDelete and onEdit called:
![eact storybook20161101161756](https://cloud.githubusercontent.com/assets/3214228/19883374/f4b3bc96-a04e-11e6-9492-e5de1b644229.gif)

**Comment by yyanwang** [comment]
My mistake, it's not a bug. the model is undefined because no props.model has been passed in.

**Comment by jmfrancois** [comment]
Nice bug report by the way 👍
