### ISSUE TITLE
bug(CircularProgress): IE11 - icon not spinning

### ISSUE THREAD

**Issue by charlesnguyen** [Talend/react-talend-components#91]
![bug circularprogress](https://cloud.githubusercontent.com/assets/13314851/20136671/5f0ac2ba-a676-11e6-8b51-86ee7e9d5b9b.png)

**Comment by acateland** [comment]
someone using windows should take on this ^^

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#41
